### ISSUE TITLE
Compatibility issue with Smooth Scrolling

### ISSUE THREAD

**Issue by SmajloSlovakian** [elmital/HighLightItem#22]
original issue: https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/issues/36

the item highlights don't scroll smoothly in the creative inventory with this mod enabled... i have made two fabric object shares which should help you improve the compatibility with this mod...
in case you don't know how to use object shares, i have this example:
```
if (FabricLoader.getInstance().getObjectShare().get("raised:hud") instanceof Integer distance) {
    doSomethingWith(distance)
}
```
the two objects i share are: "smoothsc:creative_screen/item_count" and "smoothsc:creative_screen/y_offset"
y_offset is the offset you have to move the border up or down
item_count is the count of the items to apply the offset to (i share this so you don't have to count the items inside the creative menu excluding hotbar items)
you also may have to account for the scissor (mask) which makes it so that stuff doesn't render outside the screen and so it looks better
the testing mod build can be found here in the artifacts: https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/actions/runs/9373784327

let me know if you're interested or if you have a better idea, hope this helps

**Comment by SmajloSlovakian** [comment]
i've made a pull request fixing the issues: https://github.com/elmital/HighLightItem/pull/23
it won't work with the testing build above as i needed to change some things to work but it should work with my latest commit to the dev branch

**Comment by elmital** [comment]
First thanks for your report and your PR. 
To avoid future other similars possible conflicts with other mods I've made changes (see the linked PR) that should also indirectly fix the compatibility issue with your mod. 
This more global approch even if it adds more operations avoid the dependency with external stuff which is preferable for me.
The patch is on MC 1.21 version and without a public compatible artifact of your mod I haven't tested it even if based on what i've seen in your code this should be good.

**Comment by SmajloSlovakian** [comment]
the issue is not fixed... i've updated my dev branch to 1.21 and you should be able to get the artifact from actions... i understand that you want to have more global compatibility fixes for your mods and i do as well...
i suppose you could change your approach like this: modify the conditional with the ispointoverslot method and there you could check if the item is similar to the currently highlighted slot and then modify the drawslothighlight to change the colour of the highlight... this could introduce a one-frame issue that would make everything before the highlighted slot one frame behind and i think you know that...
otherwise you could also make yourself a list of slots with their modified positions and then after the loop check every slot in your list and draw a highlight on top of them then with the correct positions... this however doesn't account for the enablescissor i apply so it would also be better not to do anything at that point...
feel free to dismiss this issue if you don't want to do stuff like this, i won't mind

**Comment by elmital** [comment]
Changes have been made while keeping the "more global approach" I wanted to. But the compatibility with your mod needs another change on your side. It's quite simple It consists in modifying the args in the HandledScreen#drawSlotHighlight instead of modifying the variable passed in the call of HandledScreen#drawSlotHighlight in HandledScreen#render method.

Actually your code : 
``` java
@ModifyVariable(method = "render", at = @At(value = "STORE"),ordinal = 6) int drawHighlightY(int y) {
    if (Config.cfg.creativeScreenSpeed == 0 || SmoothSc.creativeScreenItemCount < 0) return (y);
    return (y + SmoothSc.getCreativeDrawOffset());
}
```

Should be changed to :
``` java
@ModifyArgs(method = "drawSlotHighlight", at = @At(value = "INVOKE", target="Lnet/minecraft/client/gui/DrawContext;fillGradient(Lnet/minecraft/client/render/RenderLayer;IIIIIII)V"))
private static void drawHighlightY(Args args) {
    if (Config.cfg.creativeScreenSpeed == 0 || SmoothSc.creativeScreenItemCount < 0) return;
    args.set(2, (int) args.get(2) + SmoothSc.getCreativeScrollOffset());
    args.set(4, (int) args.get(4) + SmoothSc.getCreativeScrollOffset());
}
```

I think it's the best compromise for each other. As already said I don't want to depends on shared object from other mods I hope this change proposition will suit you. I've open a PR for that.

**Comment by SmajloSlovakian** [comment]
thanks, will look into it... just one issue (i'm going to fix) is that i need to use the draw offset instead of scroll offset because scroll offset is the actual scroll offset but draw offset is the offset i want things to draw in due to scrolling more lines at a time and stuff like that but regardless, thanks

**Comment by SmajloSlovakian** [comment]
changes have been merged, tested and a bit modified to work even better... thanks for your help!
